# core/settings.py
"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from typing import Any, List, Dict, Tuple

from utils import log_util


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR: Path = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY: str = f"{os.environ.get("SECRET_KEY")}"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG: bool = os.environ.get("BACKEND_DEBUG") == "True"

ALLOWED_HOSTS: List[str] = ["*"]

# 添加 CSRF 信任来源

CSRF_TRUSTED_ORIGINS: List[str] = [f"{os.environ.get('FRONTEND_DOMAIN')}"]

# 添加 X-Forwarded 代理支持

SECURE_PROXY_SSL_HEADER: Tuple = ("HTTP_X_FORWARDED_PROTO", "http")
USE_X_FORWARDED_HOST: bool = True

# Application definition

INSTALLED_APPS: List[str] = [
    "simpleui",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "ninja",
    "ninja_extra",
    "ninja_jwt",
    "book.apps.BookConfig",
    "account.apps.AccountConfig",
    "ai.apps.AiConfig",
]

MIDDLEWARE: List[str] = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "ninja.compatibility.files.fix_request_files_middleware",
]

ROOT_URLCONF: str = "core.urls"

TEMPLATES: List[Dict[str, Any]] = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION: str = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES: Dict[str, Dict[str, str]] = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": f"{os.environ.get('DATABASE_NAME')}",
        "USER": f"{os.environ.get('DATABASE_USER')}",
        "PASSWORD": f"{os.environ.get('DATABASE_PASSWORD')}",
        "HOST": f"{os.environ.get('DATABASE_HOST')}",
        "PORT": f"{os.environ.get('DATABASE_PORT')}",
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS: List[Dict[str, str]] = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE: str = "zh-hans"

TIME_ZONE: str = "Asia/Shanghai"

USE_I18N: bool = True

USE_TZ: bool = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL: str = "/static/"

MEDIA_URL: str = "/media/"

MEDIA_ROOT: str = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD: str = "django.db.models.BigAutoField"

# simpleui 配置
SIMPLEUI_HOME_INFO: bool = False
SIMPLEUI_DEFAULT_THEME: str = "element.css"
# SIMPLEUI_LOGO: str = ''

# log 配置
# 仅在主进程中初始化日志系统
if os.environ.get("RUN_MAIN") == "true":
    log_util.setup_logging()

# 邮箱配置
EMAIL_BACKEND: str = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST: str = "smtp.163.com"
EMAIL_PORT: int = 25
EMAIL_HOST_USER: str = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD: str = os.environ.get("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL: str = EMAIL_HOST_USER
