# Generated by Django 6.0 on 2025-12-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image_path',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='头像图片路径'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='api_key',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='API Key'),
        ),
    ]
