# Generated by Django 5.2.5 on 2025-08-29 02:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=16, verbose_name='分类名')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, verbose_name='书名')),
                ('description', models.TextField(blank=True, default='无', verbose_name='简介')),
                ('cover_image_path', models.CharField(blank=True, default='', max_length=256, verbose_name='封面图片路径')),
                ('create_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(blank=True, choices=[('serializing', '连载中'), ('completed', '已完结'), ('draft', '未发布')], default='draft', max_length=16, verbose_name='书籍状态')),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='存储书籍的属性, 如: {"is_top": false, "is_hot": true}', verbose_name='书籍属性')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.category', verbose_name='分类名')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='UserBookRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creative_role', models.CharField(blank=True, choices=[(None, '读者'), ('author', '主创'), ('co_author', '共创'), ('editor', '编辑')], default=None, max_length=16, verbose_name='创作关系')),
                ('collection_status', models.CharField(blank=True, choices=[(None, '未收藏'), ('collected', '已收藏'), ('want_to_read', '想要读'), ('reading', '正在读'), ('read', '已读完')], default=None, max_length=16, verbose_name='收藏状态')),
                ('rating', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(5)], verbose_name='评分')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relations', to='book.book', verbose_name='书籍')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '书籍-用户关系',
                'verbose_name_plural': '书籍-用户关系',
                'unique_together': {('book', 'user')},
            },
        ),
    ]
