# Generated by Django 5.2.5 on 2025-09-03 15:15

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='attributes',
            field=models.JSONField(default=dict, help_text='存储书籍的属性, 如: {"is_top": false, "is_hot": true}', verbose_name='书籍属性'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image_path',
            field=models.CharField(default='', max_length=256, verbose_name='封面图片路径'),
        ),
        migrations.AlterField(
            model_name='book',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(default='无', verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('serializing', '连载中'), ('completed', '已完结'), ('draft', '未发布')], default='draft', max_length=16, verbose_name='书籍状态'),
        ),
        migrations.AlterField(
            model_name='userbookrelation',
            name='collection_status',
            field=models.CharField(choices=[('not_collected', '未收藏'), ('collected', '已收藏'), ('want_to_read', '想要读'), ('reading', '正在读'), ('read', '已读完')], default='not_collected', max_length=16, verbose_name='收藏状态'),
        ),
        migrations.AlterField(
            model_name='userbookrelation',
            name='creative_role',
            field=models.CharField(choices=[('reader', '读者'), ('author', '主创'), ('co_author', '共创'), ('editor', '编辑')], default='reader', max_length=16, verbose_name='创作关系'),
        ),
        migrations.AlterField(
            model_name='userbookrelation',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(5)], verbose_name='评分'),
        ),
    ]
