# Generated by Django 5.2.5 on 2025-09-08 04:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_attributes_alter_book_cover_image_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='存储书籍的属性, 如: {"is_top": false, "is_hot": true}', verbose_name='书籍属性'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.category', verbose_name='分类名'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image_path',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='封面图片路径'),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chapter_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='章数')),
                ('title', models.CharField(default='', max_length=128, verbose_name='章节标题')),
                ('content', models.JSONField(blank=True, default=list, help_text='存储章节内容, 如: [{"index": 1, "type": "text", "content": "文本内容", "style": {"color": "red", "font": "SimHei"}}]', verbose_name='内容')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='draft', max_length=16, verbose_name='章节状态')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='book.book', verbose_name='所属书籍')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
                'ordering': ['chapter_number', 'create_time'],
                'unique_together': {('book', 'chapter_number')},
            },
        ),
    ]
