# Generated by Django 5.2.9 on 2025-12-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_attributes_alter_book_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='settings',
            field=models.TextField(default='', verbose_name='设定'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='outline',
            field=models.TextField(default='', verbose_name='大纲'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(default='', verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='', max_length=128, verbose_name='书名'),
        ),
    ]
