# Generated by Django 6.0 on 2025-12-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_settings_chapter_outline_alter_book_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='book',
            name='settings',
            field=models.TextField(blank=True, default='', verbose_name='设定'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='outline',
            field=models.TextField(blank=True, default='', verbose_name='大纲'),
        ),
    ]
